### PR TITLE
Reusing the "forum search" code for searching books

### PR DESCRIPTION
**Pull request by djplaner**
G'day,

I've updated the Book search block to use the same approach as the Forum search block to translating the search string into SQL.

This removes (I believe) problems with potential SQL injection attacks and enhances support for using search modifiers (" - +).

It does slightly change the performance of the search.  The prior approach would "find a chapter" only if either the title or the content contained the entire search string.  This new approach (as per the forum search) will "find a chapter" as long as the entire search string appears in some combination of the title and the content.

David.

### CODE REVIEW

**Comment by sarahjcotton** [comment]
I've adapted this to also enable users to select individual books as we have some courses that have a lot of books. While I was applying the customisation to the new update there were some **missing parameter** warnings thrown for the function **search_generate_SQL**. 
There are only 3 parameters being sent to the function which is expecting 9, so by passing 6 extra null value parameters through, these warnings can be eliminated.

Just thought I'd let you know... and thanks for the plugin, the extra search functionality is the icing on the cake!

**Comment by djplaner** [comment]
Thanks Sarah.  Adding support for choosing books is on my to do list (my course has 60+ books).  

Thanks also for picking up my poor use and testing of the search_generate_SQL function. I'm no expert dev.

Is there some way I can get hold of your changes to the block?  Am trying to convince my institution to install the block and your changes would be a big plus.

**Comment by sarahjcotton** [comment]
I'm no expert either, but that's the beauty of open source right... we get there in the end!
I've added my code to a repo with the same name as yours so you should be able to find it OK. I've used the jQuery UI accordion but I'm not entirely sure I've gone about that the correct way either however, it's there for you to do with as you wish!
I've also  left the original code in place and commented to show amendments, so you should be able to see what I've done.

**Comment by djplaner** [comment]
Thanks for the pointer, I've only had a quick skim (hoping to have more time in the coming weeks).  

It appears you've taken a slightly different approach than I did when I originally [mocked up how a search might work](https://davidtjones.wordpress.com/2015/07/19/mocking-up-a-search-facility-for-the-moodle-book-module/).  I tried to mirror the approach used by the forum search block. i.e. get to choose which book via an "advanced search" link, rather than in the normal search block.

It think it's possible that my quick and dirty test of your code is having a problem around jQuery. Rather than a small search book block, I'm seeing a very, very long block as all 60+ books are listed with checkboxes.  I'm assuming this isn't a design feature and that the accordion with all the books should actually be closed?

I can see how that might be a nicer way to do the search.  Hope to explore this a bit more soon.

**Comment by sarahjcotton** [comment]
Ah I see... well it appears I didn't include jQuery in the list of 'requires'; I guess it must have been loaded in our Moodle already (not been in this job long!) which resulted in the oversight. I don't like the way I've done that anyway and from the docs it looks like you're supposed to use: 
`
require(['jquery'], function($) {      
   });
`

Maybe just try and add in whichever version of jQuery is in your lib/jQuery folder and I'll look at trying to get the block to use jQuery and the UI correctly. At least then you'll be able to see if it's  useful to you.

**Comment by sarahjcotton** [comment]
I've added jQuery but used the pre 2.9 method rather than the new one I mentioned above... let me know how you get on!

**Comment by djplaner** [comment]
Bingo.  That's worked for my test environment.

**Comment by stronk7** [comment]
Hi,

thanks for the contribution. I did create this block quickly for a friend's site needing it and did it basically duplicating the yet older [moodle-block_search_glossaries](https://github.com/stronk7/moodle-block_search_glossaries). 2005!

Code looks perfect. Sure there is space to modernize it more, add tests and so on, but your changes are nice enough. Thanks!

**Pull request merged**
